const palavras = [
    "amada", "amora", "avestruz", "arte", "agulha", "anel", "arroz", "aro", "arco", "amigo", "abacate", "abacaxi", "abelha", "abanador", "antologia", "amor", "aba", "abraço", "ábaco", "abrigo", "abrir",
    "banana", "batalha", "bacia", "bolha", "bola", "bala", "biscoito", "bolacha", "batida", "boné", "banana", "boi", "batata", "bacalhau", "bexiga", "bowl", "batedeira", "bisturi", "barreira", "banco", 
    "cuscuz", "camomila", "cereal", "creme", "camarim", "coração", "camelo", "corpo", "corte", "carro", "caixa", "chantilly", "comércio", "cachorro", "cuidado", "caneta", "carinho", "cupuaçu", "cabra", "cesto", 
    "dado", "dinossauro", "danoninho", "desconto", "dinheiro", "dedo", "direita", "destilado", "dar", "doar", "dados", "dizer", "danone", "dente", "diário", "diamante", "diafragma", "detonar", "dia", "dromedário", 
    "escola", "escova", "enxuto", "escrivaninha", "ervilha", "elfo", "exame", "engenharia", "eletrônica", "era", "elefante", "esmeralda", "espátula", "estômago", "esfinge", "esfera", "encontro", "ema", "economia", 
    "feijoada", "farinha", "fazenda", "forca", "forma", "faca", "formiga", "fio", "fato", "focinho", "fama", "festa", "fiador", "ferver", "flauta", "fichário", "figo", "fiapo", "fotografia", 
    "geléia", "gelo", "gergelim", "geladeira", "gaveta", "girasol", "galho", "gente", "gesso", "gasto", "goiaba", "gelo", "grito", "gamão", "gíria", "goleiro", "golfinho", "golfe", "girar", "glúten",
    "humanos", "hífen", "hera", "hematoma", "hortelã", "hospital", "habilidade", "herói", "hamburguer", "hoje", "helicóptero", "harmonia", "haste", "hectare", "hábito", "hepatite", "hiena", "hemisfério", "hidrante",
    "indefesa", "imoral", "imortal", "invisível", "índio", "idoso", "imagem", "instrumento", "imã", "indivíduo", "igreja", "ícone", "importante", "ímpar", "irado", "identidade", "idioma", "idade", "idiota", 
    "jambo", "jasmim", "jabuti", "jogar", "jovem", "jornal", "janela", "justo", "jamanta", "jato", "jantar", "jumento", "jambú", "jibóia", "jararaca", "janela", "jerimum", "jaula", "jabuti", "jaleco",
    "karaokê", "karma", "kiwi", "kibon", "kalunga", "kit", "kart",
    "lagartixa", "lilás", "limão", "lavanda", "letícia", "longe", "lago", "livro", "labirinto", "linda", "laranja", "lua", "leão", "larápio", "luz", "lindo", "lacraia", "lactose", "laço", "lacrar",
    "marinha", "marmota", "mar", "molhado", "marte", "metrô", "musa", "mico", "móvel", "mirtilo", "mamão", "manga", "morango", "mico", "matar", "mingau", "moqueca", "macacão", "mocassin", "maçaneta", 
    "nuvem", "neblina", "nóz", "nitrogênio", "nada", "nadar", "nível", "níquel", "norte", "noite", "nectarina", "nada", "navio", "namorado", "ninja", "natal", "narciso", "narina", "nádega", "nabo", 
    "ovelha", "ovomaltine", "ornitorinco", "olho", "ontem", "objeto", "ordem", "oposto", "ovo", "outro", "ostra", "obstetra", "oblíquo", "orangotango", "olhar", "óculos", "ortodoxo", "ouro", "ornamento",
    "pouco", "palavra", "pombo", "piranha", "panela", "poodle", "planta", "pokémon", "público", "parte", "pato", "polvo", "povoar", "pólvora", "palhaço", "paróquia", "pano", "princesa", "pizza", "patroa", 
    "querer", "quem", "quarentena", "quermece", "quadrilha", "queijo", "quente", "quadrado", "quadra", "quentão", "quitanda", "quinta", "quantia", "quarentena", "quadrilha", "quaresma", "quartzo", "quebrar", "quarteirão",
    "ramificado", "roteiro", "risada", "ronco", "remo", "rosto", "rosa", "restaurante", "ramo", "resto", "risada", "rio", "remar", "rato", "racional", "rainha", "radioatividade", "raiz", "raiva", "rachadura", 
    "suor", "sorvete", "semáforo", "seta", "sempre", "sorte", "sorteio", "signo", "sabedoria", "sino", "salada", "salamandra", "sacola", "siri", "sábado", "safanão", "sabre", "sucarose", "sabedoria", "sacerdote", 
    "tatu", "toalha", "travesseiro", "tônico", "tratamento", "telefone", "tecla", "tempeiro", "televisão", "tomada", "tatu", "tabacaria", "taberneiro", "tábua", "torrada", "três", "terço", "tamanho", "tatuagem", "trem", 
    "uva", "umidade", "urânio", "untar", "único", "urbano", "unidimensional", "urticária", "umido", "uréia", "uísque", "união", "universo", "unanimidade", "ubuntu", "universidade", "urso", "uivar", "unir", 
    "velha", "vinho", "vermelho", "vazio", "vaso", "vela", "vestibular", "vento", "veia", "vontade", "valeta", "vacilo", "valor", "vagem", "vadiagem", "vaca", "valentia", "vidro", "valsa", 
    "wille", "wifi", "web", "waffle", "webcam",
    "xuxa", "xadrez", "xerox", "xícara", "xarope", "xilofone", "xenofobia", "xereta", "xixi", "xale", 
    "yoga", "yorkshire", "yin", "yang", "yakissoba",
    "zoológico", "zumbi", "zoeira", "zebra", "zelo","zíper", "zagueiro", "zero", "zoeira", "zodíaco", "zangão", "zepelim", "zinco",
]


export default palavras
