/*const palavras = [
    "amada", "amora", "avestruz", "arte", "agulha", "anel", "arroz", "aro", "arco", "amigo",
    "banana", "batalha", "bacia", "bolha", "bola", "bala", "biscoito", "bolacha", "batida", "bone",
    "cuscuz", "camomila", "cereal", "creme", "camarim", "coracao", "camelo", "corpo", "corte", "carro",
    "dado", "dinossauro", "danoninho", "desconto", "dinheiro", "dedo", "direita", "destilado", "dar", "doar",
    "escola", "escova", "enxuto", "escrivaninha", "ervilha", "elfo", "exame", "engenharia", "eletronica", "era",
    "feijoada", "farinha", "fazenda", "forca", "forma", "faca", "formiga", "fio", "fato", "focinho",
    "geleia", "gelo", "gergelim", "geladeira", "gaveta", "girasol", "galho", "gente", "gesso", "gasto",
    "humanos", "hifen", "hera", "hematoma", "hortela", "hospital", "habiilidade", "heroi", "hamburguer", "hoje",
    "indefesa", "imoral", "imortal", "invisivel", "indio", "idoso", "imagem", "instrumento", "ima", "individuo",
    "jambo", "jasmim", "jabuti", "jogar", "jovem", "jornal", "janela", "justo", "jamanta", "jato",
    "karaoke", "karma", "kiwi", "kibon", "kalunga", "kit", "kart",
    "lagartixa", "lilas", "limao", "lavanda", "leticia", "longe", "lago", "livro", "labirinto", "linda",
    "marinha", "marmota", "mar", "molhado", "marte", "metro", "musa", "mico", "movel", "mirtilo",
    "nuvem", "neblina", "noz", "nitrogenio", "nada", "nadar", "nivel", "niquel", "norte", "noite",
    "ovelha", "ovomaltine", "ornitorinco", "olho", "ontem", "objeto", "ordem", "oposto", "ovo", "outro",
    "pouco", "palavra", "pombo", "piranha", "panela", "poodle", "planta", "pokemon", "publico", "parte",
    "querer", "quem", "quarentena", "quermece", "quadrilha", "queijo", "quente", "quadrado", "quadra", "quentao",
    "ramificado", "roteiro", "risada", "ronco", "remo", "rosto", "rosa", "restaurante", "ramo", "resto",
    "suor", "sorvete", "semaforo", "seta", "sempre", "sorte", "sorteio", "signo", "sabedoria", "sino",
    "tatu", "toalha", "travesseiro", "tonico", "tratamento", "telefone", "tecla", "tempeiro", "televisao", "tomada",
    "uva", "umidade", "uranio", "untar", "unico", "urbano", "unidimensional", "urticaria", "umido", "ureia",
    "velha", "vinho", "vermelho", "vazio", "vaso", "vela", "vestibular", "vento", "veia", "vontade",
    "wille", "wifi", "web", "waffle", "webcam",
    "xuxa", "xadrez", "xerox", "xicara", "xarope",
    "yoga", "yorkshire", "yin", "yang", "yakissoba",
    "zoologico", "zumbi", "zoeira", "zebra", "zelo","ziper",
]*/

const palavras = [
    "abacate", "abacaxi", "abelha", "abanador", "antologia", "amor", "aba", "abraço", "ábaco", "abrigo", "abrir", 
    "banana", "boi", "batata", "bacalhau", "bexiga", "bowl", "batedeira", "bisturi", "barreira", "banco", 
    "caixa", "chantilly", "comércio", "cachorro", "cuidado", "caneta", "carinho", "cupuaçu", "cabra", "cesto", 
    "dados", "dizer", "danone", "dente", "diário", "diamante", "diafragma", "detonar", "dia", "dromedário", 
    "elefante", "esmeralda", "espátula", "estômago", "esfinge", "esfera", "encontro", "ema", "escola", "economia", 
    "formiga", "fama", "festa", "fiador", "ferver", "flauta", "fichário", "figo", "fiapo", "fotografia", 
    "goiaba", "gelo", "grito", "gamão", "guria", "goleiro", "golfinho", "golfe", "girar", "glúten", 
    "helicóptero", "harmonia", "haste", "hectare", "hábito", "hepatite", "hiena", "hemisfério", "hidrante",
    "igreja", "ícone", "importante", "ímpar", "idoso", "irado", "identidade", "idioma", "idade", "idiota", 
    "jantar", "jumento", "jambú", "jibóia", "jararaca", "janela", "jerimum", "jaula", "jabuti", "jaleco", 
    "laranja", "lua", "leão", "limão", "larápio", "luz", "lindo", "lacraia", "lactose", "laço", "lacrar", 
    "mamão", "manga", "morango", "mico", "matar", "mingau", "moqueca", "macacão", "mocassin", "maçaneta", 
    "nectarina", "nada", "navio", "namorado", "ninja", "natal", "narciso", "narina", "nádega", "nabo", 
    "ovo", "ostra", "obstetra", "oblíquo", "orangotango", "olhar", "óculos", "ortodoxo", "ouro", "ornamento", 
    "pato", "polvo", "povoar", "pólvora", "palhaço", "paróquia", "pano", "princesa", "pizza", "patroa", 
    "queijo", "quitanda", "quinta", "quantia", "quarentena", "quadrilha", "quaresma", "quartzo", "quebrar", "quarteirão", 
    "risada", "rio", "remar", "rato", "racional", "rainha", "radioatividade", "raiz", "raiva", "rachadura", 
    "salada", "salamandra", "sacola", "siri", "sábado", "safanão", "sabre", "sucarose", "sabedoria", "sacerdote", 
    "tatu", "tabacaria", "taberneiro", "tábua", "torrada", "três", "terço", "tamanho", "tatuagem", "trem", 
    "uva", "uísque", "união", "universo", "unanimidade", "ubuntu", "universidade", "urso", "uivar", "unir", 
    "vela", "valeta", "vacilo", "valor", "vagem", "vadiagem", "vaca", "valentia", "vidro", "valsa", 
    "xícara", "xadrez", "xilofone", "xarope", "xenofobia", "xereta", "xerife", "xaveco", "xixi", "xale", 
    "zebra", "zagueiro", "zero", "zoeira", "zodíaco", "zangão", "zepelim", "zinco", "zoológico", "zumbido"
]


export default palavras
