const palavras = [
    "amada", "amora", "avestruz", "arte", "agulha", "anel", "arroz", "aro", "arco", "amigo",
    "banana", "batalha", "bacia", "bolha", "bola", "bala", "biscoito", "bolacha", "batida", "bone",
    "cuscuz", "camomila", "cereal", "creme", "camarim", "coracao", "camelo", "corpo", "corte", "carro",
    "dado", "dinossauro", "danoninho", "desconto", "dinheiro", "dedo", "direita", "destilado", "dar", "doar",
    "escola", "escova", "enxuto", "escrivaninha", "ervilha", "elfo", "exame", "engenharia", "eletronica", "era",
    "feijoada", "farinha", "fazenda", "forca", "forma", "faca", "formiga", "fio", "fato", "focinho",
    "geleia", "gelo", "gergelim", "geladeira", "gaveta", "girasol", "galho", "gente", "gesso", "gasto",
    "humanos", "hifen", "hera", "hematoma", "hortela", "hospital", "habiilidade", "heroi", "hamburguer", "hoje",
    "indefesa", "imoral", "imortal", "invisivel", "indio", "idoso", "imagem", "instrumento", "ima", "individuo",
    "jambo", "jasmim", "jabuti", "jogar", "jovem", "jornal", "janela", "justo", "jamanta", "jato",
    "karaoke", "karma", "kiwi", "kibon", "kalunga", "kit", "kart",
    "lagartixa", "lilas", "limao", "lavanda", "leticia", "longe", "lago", "livro", "labirinto", "linda",
    "marinha", "marmota", "mar", "molhado", "marte", "metro", "musa", "mico", "movel", "mirtilo",
    "nuvem", "neblina", "noz", "nitrogenio", "nada", "nadar", "nivel", "niquel", "norte", "noite",
    "ovelha", "ovomaltine", "ornitorinco", "olho", "ontem", "objeto", "ordem", "oposto", "ovo", "outro",
    "pouco", "palavra", "pombo", "piranha", "panela", "poodle", "planta", "pokemon", "publico", "parte",
    "querer", "quem", "quarentena", "quermece", "quadrilha", "queijo", "quente", "quadrado", "quadra", "quentao",
    "ramificado", "roteiro", "risada", "ronco", "remo", "rosto", "rosa", "restaurante", "ramo", "resto",
    "suor", "sorvete", "semaforo", "seta", "sempre", "sorte", "sorteio", "signo", "sabedoria", "sino",
    "tatu", "toalha", "travesseiro", "tonico", "tratamento", "telefone", "tecla", "tempeiro", "televisao", "tomada",
    "uva", "umidade", "uranio", "untar", "unico", "urbano", "unidimensional", "urticaria", "umido", "ureia",
    "velha", "vinho", "vermelho", "vazio", "vaso", "vela", "vestibular", "vento", "veia", "vontade",
    "wille", "wifi", "web", "waffle", "webcam",
    "xuxa", "xadrez", "xerox", "xicara", "xarope",
    "yoga", "yorkshire", "yin", "yang", "yakissoba",
    "zoologico", "zumbi", "zoeira", "zebra", "zelo","ziper",
]

export default palavras
